### ISSUE TITLE
Developer Section maybe added

### ISSUE THREAD

**Issue by gazalk** [S-John-S/MAT#1]
Do you think we should add developer section? For  people who want to join us, a brief intro can given on website. Like: Documentation, git instructions, etc.

**Comment by S-John-S** [comment]
OK. I will take a look at that aspect.

**Comment by gazalk** [comment]
Ok, So for now we only keep 'Join Us' and some brief explanation there. When we make our code open, we'll put the developer section.

**Comment by S-John-S** [comment]
Understood.

**Comment by S-John-S** [comment]
Now in the nascent phase, it has been shortened.
